### ISSUE TITLE
Edit 

### ISSUE THREAD

**Issue by InvasiveLionfish** [learn-co-curriculum/sinatra-activerecord-associations#11]
Hope I'm doing this correctly.

Currently the Owner Model class shows the association as "has_many :cat"
Should be "has_many :cats"

Made the changes and submitted PR.

**Comment by AnnJohn** [comment]
hi @InvasiveLionfish, didn't see a PR so can you try and making it again. In the lesson on Learn, you can  click on an icon at the top that will let you edit the lesson. This, on our end, will open up a PR. 

Thanks!
