### ISSUE TITLE
Examples look wrong

### ISSUE THREAD

**Issue by milespucarelli** [learn-co-curriculum/sinatra-activerecord-associations#18]
In the README the code examples setting up the Cat and Owner classes need to inherit from ActiveRecord::Base.

**Comment by rcho100** [comment]
They actually need to inherit from ActiveRecord::Migration. The code in the actual migration files reflect this.

**Comment by drakeltheryuujin** [comment]
Thanks for your feedback! We have updated the materials and believe your issue to have been resolved.
