### ISSUE TITLE
class defined as ActiveRecord::Base in migration file

### ISSUE THREAD

**Issue by jenniferbusca** [learn-co-curriculum/sinatra-activerecord-associations#19]
<img width="921" alt="Screen Shot 2019-07-01 at 4 12 07 PM" src="https://user-images.githubusercontent.com/25334564/60463840-04cb6780-9c1b-11e9-95eb-f8751534796a.png">
I believe that the code within the migration should be 
class CreateCats < ActiveRecord::Migration rather than 
class CreateCats < ActiveRecord::Base as shown in the screenshot

**Comment by drakeltheryuujin** [comment]
Thanks for your feedback! We have updated the materials and believe your issue to have been resolved.
